//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDoctor()
        {
            this.tblAppointments = new HashSet<tblAppointment>();
        }
    
        public int Doctor_Id { get; set; }
        public string Doctor_Name { get; set; }
        public string Doctor_Surname { get; set; }
        public string Doctor_Email { get; set; }
        public int Doctor_ContactNO { get; set; }
        public string Doctor_ID_NO { get; set; }
        public string Doctor_Type { get; set; }
        public byte[] Doctor_Image { get; set; }
        public string Doctor_Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAppointment> tblAppointments { get; set; }
    }
}
