//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoice
    {
        public int Bill_Id { get; set; }
        public System.DateTime Bill_Date { get; set; }
        public string Appointment_Code { get; set; }
        public string Bill_Code { get; set; }
        public string Patient_Code { get; set; }
    
        public virtual tblAppointment tblAppointment { get; set; }
        public virtual tblPatient tblPatient { get; set; }
    }
}
