//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblPatient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPatient()
        {
            this.tblAppointments = new HashSet<tblAppointment>();
            this.tblInvoices = new HashSet<tblInvoice>();
        }
    
        public int Patient_Id { get; set; }
        public string Patient_Name { get; set; }
        public int Patient_Age { get; set; }
        public string Patient_Code { get; set; }
        [DataType(DataType.Password )]
        public string Patient_Password { get; set; }
        public string Patient_ID_NO { get; set; }
        public string Patient_Address { get; set; }
        public Nullable<int> Patient_ContactNO { get; set; }
        public System.DateTime Patient_DOB { get; set; }
        public string Patien_Surname { get; set; }
        public byte[] Patient_Image { get; set; }
        public string Patient_Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAppointment> tblAppointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInvoice> tblInvoices { get; set; }
    }
}
